
<html>
<body>

  <h1>hi</h1>
  <script>
  
  // Promises
  function getWeather(cityId) {
    fetch(`https://www.metaweather.com/api/location/${cityId}/`)
    .then(res => {
      return res.json();
    })
    .then(data => console.log(data.title))
    // handle the error
    .catch(err => console.log(err))
  }

  // async/await 
  async function getWeather2(cityId) {
    // use try-catch to handle errors 
    try {
      const result = await fetch(`https://www.metaweather.com/api/location/${cityId}/`);
      const data = await result.json();
      console.log(data.title);
    } catch (error) {
      console.log(error);
    }
  }

  // Calling the functioons
  getWeather(2487956);

  // an async function returns a promise you can use it calling the fucntion with .then at the end
  getWeather2(2487956);

  console.log('hello');
  
  </script>
</body>
</html>